spring:
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 1066712321564-f6n95oo8bc7k54puk3tcj4o5hfe4nkbh.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile
                    
         facebook:
          clientId: 405587784763894
          clientSecret: 1f4f4ef50ee3c88ee868f35321c1d524
          scope:
           - email
           - public_profile
