spring:
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 1066712321564-f6n95oo8bc7k54puk3tcj4o5hfe4nkbh.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile
                    
         facebook:
          clientId: YOUR_FACEBOOK_APP_CLIENT_ID
          clientSecret: YOUR_FACEBOOK_APP_SECRET_KEY
          scope:
           - email
           - public_profile
